export const projects = [
  {
    id: "pixelmind",
    name: "PixelMind",
    description: "AI 图像工作台与无限画布",
    color: "#4057f4",
    repo: "pixelmind/pixelmind",
    provider: "Gitea · 自建",
    localWorkspace: {
      path: "D:\\Projects\\PixelMind",
      branch: "feat/canvas-grid",
      head: "9ae42a1",
      dirtyFiles: 2,
      ahead: 3,
      behind: 0,
      worktrees: 3,
      lastScan: "刚刚",
      watcher: "online",
    },
    milestone: "M2 · Canvas 协作闭环",
    milestoneProgress: 68,
    due: "8 月 29 日",
    status: "active",
    health: "正常推进",
    focusHours: 12.6,
    worktrees: 3,
    agents: 2,
    lastActivity: "12 分钟前",
    next: "完成画布网格渲染验收",
  },
  {
    id: "edgemind",
    name: "EdgeMind",
    description: "设备自动化与协议运行平台",
    color: "#7c5ce5",
    repo: "mingke/edgemind",
    provider: "GitHub",
    milestone: "M1 · Worker 稳定性",
    milestoneProgress: 42,
    due: "9 月 6 日",
    status: "risk",
    health: "3 天未推进",
    focusHours: 1.4,
    worktrees: 2,
    agents: 1,
    lastActivity: "3 天前",
    next: "确认设备租约回收策略",
  },
  {
    id: "content-studio",
    name: "Content Studio",
    description: "素材生产、审阅与发布桌面端",
    color: "#18a97a",
    repo: "mingke/content-studio",
    provider: "Gitea · 自建",
    milestone: "M3 · Desktop Migration",
    milestoneProgress: 81,
    due: "8 月 24 日",
    status: "active",
    health: "等待验收",
    focusHours: 4.2,
    worktrees: 1,
    agents: 1,
    lastActivity: "昨天 22:16",
    next: "完成安装包 smoke test",
  },
  {
    id: "protocol-runtime",
    name: "Protocol Runtime",
    description: "协议组件和设备能力运行时",
    color: "#ec8b22",
    repo: "dewu/runtime",
    provider: "GitHub",
    milestone: "M5 · Bundle v20",
    milestoneProgress: 24,
    due: "9 月 18 日",
    status: "paused",
    health: "暂缓",
    focusHours: 0,
    worktrees: 1,
    agents: 0,
    lastActivity: "7 天前",
    next: "补齐真实设备验收证据",
  },
];

export const todayTasks = [
  { id: 1, title: "画布网格渲染验收", project: "PixelMind", duration: 50, state: "now", agent: "你", milestone: "M2" },
  { id: 2, title: "设备租约回收策略", project: "EdgeMind", duration: 35, state: "next", agent: "Codex", milestone: "M1" },
  { id: 3, title: "桌面安装包 smoke test", project: "Content Studio", duration: 30, state: "next", agent: "Agent · Luna", milestone: "M3" },
  { id: 4, title: "整理语音 Inbox", project: "个人系统", duration: 15, state: "later", agent: "你", milestone: "维护" },
  { id: 5, title: "Bundle v20 验收清单", project: "Protocol Runtime", duration: 25, state: "later", agent: "Codex", milestone: "M5" },
];

export const inboxSeed = [
  { id: 1, title: "知识图谱节点可以显示最近一次 Agent 输出", note: "@知识图谱 @工作树，节点 hover 时直接看摘要", source: "语音", created: "11:38", project: "未归类", kind: "想法" },
  { id: 2, title: "Canvas 网格性能需要在低端设备上做一次基准", note: "可能放进 M2 的验收计划", source: "快捷记录", created: "10:12", project: "PixelMind", kind: "需求" },
  { id: 3, title: "EdgeMind 的 lease cleanup 应该有 dry-run", note: "Agent 可以先生成影响列表，再让人确认", source: "Agent", created: "昨天", project: "EdgeMind", kind: "风险" },
  { id: 4, title: "每周自动生成所有项目的停滞报告", note: "按 24h / 3d / 7d 分级，并推荐下一步", source: "语音", created: "昨天", project: "未归类", kind: "想法" },
  { id: 5, title: "Gitea Webhook 应该保留签名失败证据", note: "关联到项目日志和对应工作树", source: "导入", created: "周一", project: "Agentic Project OS", kind: "需求" },
];

export const milestones = [
  { id: "m2", name: "M2 · Canvas 协作闭环", progress: 68, date: "8 月 29 日", status: "active", plans: 3, tasks: 14, done: 9, color: "#4057f4" },
  { id: "m3", name: "M3 · Agent 自动整理", progress: 34, date: "9 月 12 日", status: "planned", plans: 4, tasks: 18, done: 6, color: "#7c5ce5" },
  { id: "m4", name: "M4 · 多人 Review", progress: 0, date: "10 月 3 日", status: "planned", plans: 2, tasks: 8, done: 0, color: "#18a97a" },
];

export const worktrees = [
  { id: "canvas-grid", branch: "feat/canvas-grid", path: "~/Projects/PixelMind/.worktrees/canvas-grid", agent: "Codex", status: "running", activity: "12 分钟前", task: "#128 Improve grid rendering", output: "3 commits · 11 files", blocker: "等待视觉验收", commits: ["9ae42a1", "04f9ca8"] },
  { id: "agent-link", branch: "feat/agent-link", path: "~/Projects/PixelMind/.worktrees/agent-link", agent: "Agent · Luna", status: "review", activity: "38 分钟前", task: "MCP 双向链接写入", output: "PR #131 · 通过 18 项测试", blocker: "无", commits: ["8c2b013"] },
  { id: "main", branch: "main", path: "~/Projects/PixelMind", agent: "你", status: "idle", activity: "今天 09:46", task: "整理 M2 验收范围", output: "工作区干净", blocker: "2 个 Inbox 待决策", commits: ["4cc19dd"] },
];

export const projectTasks = [
  { id: 1, title: "Infinite Canvas", type: "plan", milestone: "M2", progress: 72, children: 4, status: "doing" },
  { id: 2, title: "画布网格渲染验收", type: "task", milestone: "M2", progress: 64, parent: "Infinite Canvas", status: "doing", owner: "你", due: "今天" },
  { id: 3, title: "合并 feat/canvas-grid", type: "task", milestone: "M2", progress: 40, parent: "Infinite Canvas", status: "review", owner: "Codex", due: "今天" },
  { id: 4, title: "Agent Link Protocol", type: "plan", milestone: "M3", progress: 35, children: 6, status: "doing" },
  { id: 5, title: "MCP 写入关系实体", type: "task", milestone: "M3", progress: 80, parent: "Agent Link Protocol", status: "review", owner: "Agent · Luna", due: "明天" },
  { id: 6, title: "语音 Inbox 自动分类", type: "task", milestone: "M3", progress: 15, parent: "Agent Link Protocol", status: "todo", owner: "Codex", due: "周五" },
];

export const projectLogs = [
  { time: "11:48", actor: "Codex", action: "更新工作树", detail: "feat/canvas-grid 完成 3 次提交并请求视觉验收", type: "agent" },
  { time: "11:32", actor: "Gitea", action: "收到 push", detail: "9ae42a1 perf(canvas): reduce grid redraws", type: "git" },
  { time: "10:56", actor: "你", action: "调整里程碑", detail: "M2 截止时间从 8 月 27 日调整到 8 月 29 日", type: "human" },
  { time: "10:18", actor: "Agent · Luna", action: "关联想法", detail: "将“思维导图 @ 工作树”链接到 MCP 双向链接任务", type: "agent" },
  { time: "昨天 22:04", actor: "系统", action: "生成日报", detail: "PixelMind 今日投入 3h42m，完成 4 个任务", type: "system" },
];

export const graphSeed = {
  nodes: [
    { id: "PixelMind", label: "PixelMind", type: "project", val: 12 },
    { id: "EdgeMind", label: "EdgeMind", type: "project", val: 10 },
    { id: "Content Studio", label: "Content Studio", type: "project", val: 9 },
    { id: "M2", label: "M2 · Canvas 协作闭环", type: "milestone", val: 7 },
    { id: "M3", label: "M3 · Agent 自动整理", type: "milestone", val: 7 },
    { id: "canvas-grid", label: "feat/canvas-grid", type: "worktree", val: 6 },
    { id: "agent-link", label: "feat/agent-link", type: "worktree", val: 6 },
    { id: "task-grid", label: "画布网格渲染验收", type: "task", val: 5 },
    { id: "task-mcp", label: "MCP 写入关系实体", type: "task", val: 5 },
    { id: "idea-hover", label: "节点显示 Agent 输出", type: "idea", val: 4 },
    { id: "idea-dry", label: "Lease cleanup dry-run", type: "idea", val: 4 },
    { id: "log-1", label: "9ae42a1", type: "commit", val: 3 },
    { id: "log-2", label: "PR #131", type: "commit", val: 3 },
    { id: "agent-codex", label: "Codex", type: "agent", val: 5 },
    { id: "agent-luna", label: "Agent · Luna", type: "agent", val: 5 },
  ],
  links: [
    { source: "PixelMind", target: "M2", relation: "包含" },
    { source: "PixelMind", target: "M3", relation: "包含" },
    { source: "PixelMind", target: "canvas-grid", relation: "工作树" },
    { source: "PixelMind", target: "agent-link", relation: "工作树" },
    { source: "M2", target: "task-grid", relation: "计划" },
    { source: "M3", target: "task-mcp", relation: "计划" },
    { source: "canvas-grid", target: "task-grid", relation: "执行" },
    { source: "agent-link", target: "task-mcp", relation: "执行" },
    { source: "idea-hover", target: "canvas-grid", relation: "@工作树" },
    { source: "idea-hover", target: "PixelMind", relation: "@项目" },
    { source: "canvas-grid", target: "log-1", relation: "产出" },
    { source: "agent-link", target: "log-2", relation: "产出" },
    { source: "agent-codex", target: "canvas-grid", relation: "负责" },
    { source: "agent-luna", target: "agent-link", relation: "负责" },
    { source: "EdgeMind", target: "idea-dry", relation: "想法" },
    { source: "PixelMind", target: "Content Studio", relation: "共享组件" },
  ],
};

export const nodeColors = {
  project: "#5f6ff7",
  milestone: "#a27bf3",
  plan: "#668eea",
  worktree: "#2ac49b",
  task: "#f2a33a",
  idea: "#ee6e9f",
  canvas_node: "#8d79dd",
  inbox_item: "#e6b43c",
  proposal: "#ef7c58",
  remote_repository: "#65a633",
  commit: "#8b97ad",
  agent: "#42b8e8",
};
